### ISSUE TITLE
Staticman form not working

### ISSUE THREAD

**Issue by VincentTam** [zinefer/zinefer.github.com#349]
# Description

As in title.

# Steps to reproduce

Submit a comment in any post.

# Screenshot

![Screenshot from 2021-02-26 11-33-32](https://user-images.githubusercontent.com/5748535/109289695-dbffd900-7826-11eb-83ed-0d503c4a20bd.png)

# Analysis

This is a server-side problem. The former public testing instance `dev.staticman.net`, which was hosted on a Heroku dyno in the free tier, is no longer being maintained. Staticman's maintainer has recommended users to self-host their own instance in the comments in issue 317.  For a quick API instance setup guide, you may consult the update official tutorial:
https://staticman.net/docs/getting-started.html

**Comment by zinefer** [comment]
Thanks!
